[package]
edition = "2021"
name = "posts"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "posts"

[dependencies]
serde = "1"
derive_more = "0"

hdk = "0.0.142"
private_publication_integrity = {git = "https://github.com/holochain-immersive/zomes", branch = "main"}
