[package]
edition = "2021"
name = "profiles"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles"

[dependencies]
serde = "1"
derive_more = "0"
profiles_integrity = { path = "../../integrity_zomes/profiles" }

hdk = "0.0.142"
